///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//It represents the Java object 'CFixStateConstants_interface'.
//This file includs the necessary wrappings for the JNI calls to the Java object.


#if !defined COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CFIXSTATECONSTANTS_INTERFACE_H
	#define COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CFIXSTATECONSTANTS_INTERFACE_H



#include "com/mintech/utils/fmi/JNIException.h"
#include "com/mintech/utils/fmi/JNIError.h"
#include "com/mintech/utils/fmi/FMIException.h"
#include "java/lang/Object_interface.h"

#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} //Close namespace


using namespace com::mintech::utils::fmi;
using namespace com::mintech::utils::fmi::builtin::arrays;

namespace com{
	namespace sungard{
		namespace cs{
			namespace fix{
				namespace fixgateway{
					namespace api{
						namespace capi{
class CFixStateConstants_interface;

class DLL_EXPORT CFixStateConstants_interface : public java::lang::Object_interface
{
public:
//Public Methods
	//Destructor
	virtual ~CFixStateConstants_interface() { }


	//get method for the object name
	virtual const char* getFullName() = 0;

	//get / set methods for the Java object reference
	virtual jobject getReference() const		{ return m_ref;	}

	virtual void setReference(jobject ref)		{ m_ref = ref;	}

};

}}}}}}} //Close namespace



#endif
