///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'com.sungard.cs.fix.fixgateway.api.capi.CFixEngineFactory



#if !defined COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CFIXENGINEFACTORY_H
	#define COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CFIXENGINEFACTORY_H


#include "com/sungard/cs/fix/fixgateway/api/capi/CFixEngineFactory_stub.h"


//These incudes are needed for the methods of the Stub


using namespace com::mintech::utils::fmi;

namespace com{
	namespace sungard{
		namespace cs{
			namespace fix{
				namespace fixgateway{
					namespace api{
						namespace capi{

class CFixEngineFactory;


class DLL_EXPORT CFixEngineFactory : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//CFixEngineFactory Public methods
	/* throws java.lang.Exception */
	static 	com::sungard::cs::fix::fixgateway::api::capi::CManagedAPI createFixEngine(const CProperties& p1);

	/* throws java.lang.Exception */
	static 	com::sungard::cs::fix::fixgateway::api::capi::CProperties createProperties(const string& p1);

	/* throws java.lang.Exception */
	static 	com::sungard::cs::fix::fixgateway::api::capi::CLogFactory createLogFactory(const string& p1, const CProperties& p2);

//End of CFixEngineFactory Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	CFixEngineFactory();

	//Copy constructor
	CFixEngineFactory(const CFixEngineFactory& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	CFixEngineFactory(CFixEngineFactory_stub* stub);

	//Constructor with jobject for returned objects
	CFixEngineFactory(jobject obj);

	//Constructor with const int for handling NULL
	CFixEngineFactory(const int null);

	//Set the stub
	void setStub(CFixEngineFactory_stub* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	CFixEngineFactory& operator=(const CFixEngineFactory& copy);

	//operator= for NULL
	CFixEngineFactory& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(CFixEngineFactory& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(CFixEngineFactory& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);
};


}}}}}}} //Close namespace



#endif
