///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'com.sungard.cs.fix.fixgateway.api.capi.CFixListenerRef



#if !defined COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CFIXLISTENERREF_H
	#define COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CFIXLISTENERREF_H


#include "com/sungard/cs/fix/fixgateway/api/capi/CFixListenerRef_stub.h"


//These incudes are needed for the methods of the Stub


using namespace com::mintech::utils::fmi;

namespace com{
	namespace sungard{
		namespace cs{
			namespace fix{
				namespace fixgateway{
					namespace api{
						namespace capi{

class CFixListenerRef;


class DLL_EXPORT CFixListenerRef : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//CFixListenerRef Public methods
	static 	com::sungard::cs::fix::fixgateway::api::capi::CFixListenerRef createListener(const jint p1);

//End of CFixListenerRef Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	CFixListenerRef();

	//Copy constructor
	CFixListenerRef(const CFixListenerRef& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	CFixListenerRef(CFixListenerRef_stub* stub);

	//Constructor with jobject for returned objects
	CFixListenerRef(jobject obj);

	//Constructor with const int for handling NULL
	CFixListenerRef(const int null);

	//Set the stub
	void setStub(CFixListenerRef_stub* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	CFixListenerRef& operator=(const CFixListenerRef& copy);

	//operator= for NULL
	CFixListenerRef& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(CFixListenerRef& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(CFixListenerRef& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);
};


}}}}}}} //Close namespace



#endif
