///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'CFixStatus'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPICFIXSTATUS_STUB_H
	#define COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPICFIXSTATUS_STUB_H


#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} // close namespace

namespace java{
	namespace lang{
class Object;
}} // close namespace

namespace java{
	namespace lang{
class Class;
}} // close namespace


using com::mintech::utils::fmi::JNIException;
using com::mintech::utils::fmi::builtin::arrays::FObjectArray;
using java::lang::Object;
using java::lang::Class;

namespace com{
	namespace sungard{
		namespace cs{
			namespace fix{
				namespace fixgateway{
					namespace api{
						namespace capi{
class CFixStatus_stub;


class DLL_EXPORT CFixStatus_stub : public Object_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	CFixStatus_stub();

	// constructor with jobject parameter for methods that return this object
	CFixStatus_stub(jobject obj);

	// destructor
	~CFixStatus_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//CFixStatus Public methods
	jint getFixState();

	jint getPrevFixState();

	string getMessageFormat();

	jint getExpectedInSeqNum();

	jint getExpectedOutSeqNum();

	jint getOutQueueSize();

	string getStateReasonText();

	jint getStateReasonCode();

	string getSenderCompID();

	string getTargetCompID();

	string getSessionID();

	string getCommString();

	FObjectArray getSupportedSend();

	FObjectArray getSupportedReceive();

	string getSupportedSendStr();

	string getSupportedReceiveStr();

//////////////////////////////////
// end of CFixStatus Public methods

//////////////////////////////
// public data members methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;
	static jmethodID method_5_ID;
	static jmethodID method_6_ID;
	static jmethodID method_7_ID;
	static jmethodID method_8_ID;
	static jmethodID method_9_ID;
	static jmethodID method_10_ID;
	static jmethodID method_11_ID;
	static jmethodID method_12_ID;
	static jmethodID method_13_ID;
	static jmethodID method_14_ID;
	static jmethodID method_15_ID;
	static jmethodID method_16_ID;
	static jmethodID method_17_ID;
};


}}}}}}} // close namespace

#endif
