///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'com.sungard.cs.fix.fixgateway.api.capi.CSessionID



#if !defined COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CSESSIONID_H
	#define COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CSESSIONID_H


#include "com/sungard/cs/fix/fixgateway/api/capi/CSessionID_stub.h"


//These incudes are needed for the methods of the Stub


using namespace com::mintech::utils::fmi;

namespace com{
	namespace sungard{
		namespace cs{
			namespace fix{
				namespace fixgateway{
					namespace api{
						namespace capi{

class CSessionID;


class DLL_EXPORT CSessionID : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//CSessionID Public methods
	static 	string calc(const CProperties& p1);

	static 	string calc(const string& p1, const string& p2);

	static 	string calcSender(const string& p1);

	static 	string calcTarget(const string& p1);

	/* throws com.sungard.cs.fix.fixgateway.api.FIXException */
	static 	string calcMessageSessionID(const string& p1, const jboolean p2);

//End of CSessionID Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	CSessionID();

	//Copy constructor
	CSessionID(const CSessionID& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	CSessionID(CSessionID_stub* stub);

	//Constructor with jobject for returned objects
	CSessionID(jobject obj);

	//Constructor with const int for handling NULL
	CSessionID(const int null);

	//Set the stub
	void setStub(CSessionID_stub* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	CSessionID& operator=(const CSessionID& copy);

	//operator= for NULL
	CSessionID& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(CSessionID& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(CSessionID& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);
};


}}}}}}} //Close namespace



#endif
