///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'com.sungard.cs.fix.fixgateway.api.capi.CStatesEnum



#if !defined COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CSTATESENUM_H
	#define COM_SUNGARD_CS_FIX_FIXGATEWAY_API_CAPI_CSTATESENUM_H


#include "com/sungard/cs/fix/fixgateway/api/capi/CStatesEnum_stub.h"


//These incudes are needed for the methods of the Stub


using namespace com::mintech::utils::fmi;

namespace com{
	namespace sungard{
		namespace cs{
			namespace fix{
				namespace fixgateway{
					namespace api{
						namespace capi{

class CStatesEnum;


class DLL_EXPORT CStatesEnum : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//CStatesEnum Public methods
	bool hasMoreElements();

	/* throws java.util.NoSuchElementException */
	jint nextElement();

//End of CStatesEnum Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	CStatesEnum();

	//Copy constructor
	CStatesEnum(const CStatesEnum& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	CStatesEnum(CStatesEnum_stub* stub);

	//Constructor with jobject for returned objects
	CStatesEnum(jobject obj);

	//Constructor with const int for handling NULL
	CStatesEnum(const int null);

	//Set the stub
	void setStub(CStatesEnum_stub* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	CStatesEnum& operator=(const CStatesEnum& copy);

	//operator= for NULL
	CStatesEnum& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(CStatesEnum& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(CStatesEnum& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);
};


}}}}}}} //Close namespace



#endif
