INSERT INTO UG_UGATE (UGID,UGNAME,R_DESTNO,R_FUNCNO,R_SNO,STATUS,LASTTIME) VALUES ('CYHUG1','FIX-UG on CYH-PC',100,5910,0,0,0);

INSERT INTO UG_PARTNER (PARTNERID,PARTNERNAME,TYPE,ORDERID_FMT,CLORDID_FMT,EOD_TIME) VALUES ('GL','Global Trading BS/SS',0,'gl%5d','cl%d','04:00:00');

INSERT INTO UG_CHANNEL (  PARTNERID, UGID, VELOCITY, STATUS) VALUES ('GL','CYHUG1',10,0);



