
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JApiListener */
#ifndef _Included_com_mint_fixgateway_api_capi_cbapi
#define _Included_com_mint_fixgateway_api_capi_cbapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mint_fixgateway_api_capi_cbapi_handleAsyncError_handleStateChanged
 * Method:    handleStateChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mint_fixgateway_api_capi_JApiListener_handleStateChanged
  (JNIEnv *, jobject, jint, jstring, jint, jint, jint, jstring);


/*
 * Class:     com_mint_fixgateway_api_capi_cbapi_handleAsyncError_handleMessageReceived
 * Method:    handleMessageReceived
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mint_fixgateway_api_capi_JApiListener_handleMessageReceived
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mint_fixgateway_api_capi_cbapi_handleAsyncError
 * Method:    handleAsyncError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mint_fixgateway_api_capi_JApiListener_handleAsyncError
  (JNIEnv *, jobject, jint, jstring, jint, jstring, jthrowable);


#ifdef __cplusplus
}
#endif
#endif