///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.security.CodeSource



#if !defined JAVA_SECURITY_CODESOURCE_H
	#define JAVA_SECURITY_CODESOURCE_H


#include "java/security/CodeSource_stub.h"


//These incudes are needed for the methods of the Stub
#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace security{

class CodeSource;


class DLL_EXPORT CodeSource : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//CodeSource Public methods
	FObjectArray getCertificates();

	java::net::URL getLocation();

	bool implies(const CodeSource& p1);

	FObjectArray getCodeSigners();

//End of CodeSource Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	CodeSource();

	//Copy constructor
	CodeSource(const CodeSource& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	CodeSource(CodeSource_stub* stub);

	//Constructor with jobject for returned objects
	CodeSource(jobject obj);

	//Constructor with const int for handling NULL
	CodeSource(const int null);

	//Set the stub
	void setStub(CodeSource_stub* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	CodeSource& operator=(const CodeSource& copy);

	//operator= for NULL
	CodeSource& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(CodeSource& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(CodeSource& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);
};


}} //Close namespace



#endif
