///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.security.CodeSigner



#if !defined JAVA_SECURITY_CODESIGNER_H
	#define JAVA_SECURITY_CODESIGNER_H


#include "java/security/CodeSigner_stub.h"


//These incudes are needed for the methods of the Stub


using namespace com::mintech::utils::fmi;

namespace java{
	namespace security{

class CodeSigner;


class DLL_EXPORT CodeSigner : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//CodeSigner Public methods
	java::security::cert::CertPath getSignerCertPath();

	java::security::Timestamp getTimestamp();

//End of CodeSigner Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	CodeSigner();

	//Copy constructor
	CodeSigner(const CodeSigner& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	CodeSigner(CodeSigner_stub* stub);

	//Constructor with jobject for returned objects
	CodeSigner(jobject obj);

	//Constructor with const int for handling NULL
	CodeSigner(const int null);

	//Set the stub
	void setStub(CodeSigner_stub* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	CodeSigner& operator=(const CodeSigner& copy);

	//operator= for NULL
	CodeSigner& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(CodeSigner& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(CodeSigner& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);
};


}} //Close namespace



#endif
