///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'Key'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_SECURITYKEY_STUB_H
	#define JAVA_SECURITYKEY_STUB_H


#include "java/security/Key_interface.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FByteArray;
}}}}}} // close namespace

namespace java{
	namespace security{
class Key;
}} // close namespace

namespace java{
	namespace io{
class Serializable;
}} // close namespace


using com::mintech::utils::fmi::JNIException;
using com::mintech::utils::fmi::builtin::arrays::FByteArray;
using java::security::Key;
using java::io::Serializable;

namespace java{
	namespace security{
class Key_stub;


class DLL_EXPORT Key_stub : public Key_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	Key_stub();

	// constructor with jobject parameter for methods that return this object
	Key_stub(jobject obj);

	// destructor
	~Key_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//Key Public methods
	string getAlgorithm();

	FByteArray getEncoded();

	string getFormat();

//////////////////////////////////
// end of Key Public methods

//////////////////////////////
// public data members methods
	////////////////////////////////////////
	// public data members retrieval methods
	//'final' fields
	static jlong get_serialVersionUID();

	//////////////////////////////////
	// public data members set methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;

	// IDs for static data members
	static jfieldID staticField_1_ID;

};


}} // close namespace

#endif
