///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.security.Principal



#if !defined JAVA_SECURITY_PRINCIPAL_H
	#define JAVA_SECURITY_PRINCIPAL_H


#include "java/security/Principal_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/security/Principal_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace security{

class Principal;


class DLL_EXPORT Principal : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//Principal Public methods
	string getName();

//End of Principal Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	Principal();

	//Copy constructor
	Principal(const Principal& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	Principal(Principal_stub* stub);

	//Constructor with jobject for returned objects
	Principal(jobject obj);

	//Constructor with const int for handling NULL
	Principal(const int null);

	//Set the stub
	void setStub(Principal_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	Principal& operator=(const Principal& copy);

	//operator= for NULL
	Principal& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(Principal& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(Principal& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static Principal castFrom_Object(const Object& base);
};


}} //Close namespace



#endif
