///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'ProtectionDomain'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_SECURITYPROTECTIONDOMAIN_STUB_H
	#define JAVA_SECURITYPROTECTIONDOMAIN_STUB_H


#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} // close namespace

namespace java{
	namespace lang{
class ClassLoader;
}} // close namespace

namespace java{
	namespace security{
class CodeSource;
}} // close namespace

namespace java{
	namespace security{
class PermissionCollection;
}} // close namespace

namespace java{
	namespace security{
class Principal;
}} // close namespace

namespace java{
	namespace security{
class Permission;
}} // close namespace

namespace java{
	namespace lang{
class Class;
}} // close namespace

namespace java{
	namespace lang{
class Object;
}} // close namespace


using com::mintech::utils::fmi::JNIException;
using com::mintech::utils::fmi::builtin::arrays::FObjectArray;
using java::lang::ClassLoader;
using java::security::CodeSource;
using java::security::PermissionCollection;
using java::security::Principal;
using java::security::Permission;
using java::lang::Class;
using java::lang::Object;

namespace java{
	namespace security{
class ProtectionDomain_stub;


class DLL_EXPORT ProtectionDomain_stub : public Object_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	ProtectionDomain_stub();

	// constructor with jobject parameter for methods that return this object
	ProtectionDomain_stub(jobject obj);

	// destructor
	~ProtectionDomain_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//ProtectionDomain Public methods
	java::lang::ClassLoader getClassLoader();

	java::security::CodeSource getCodeSource();

	java::security::PermissionCollection getPermissions();

	FObjectArray getPrincipals();

	bool implies(const Permission& p1);

//////////////////////////////////
// end of ProtectionDomain Public methods

//////////////////////////////
// public data members methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;
	static jmethodID method_5_ID;
	static jmethodID method_6_ID;

};


}} // close namespace

#endif
