///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//It represents the Java object 'PublicKey_interface'.
//This file includs the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_SECURITY_PUBLICKEY_INTERFACE_H
	#define JAVA_SECURITY_PUBLICKEY_INTERFACE_H



#include "com/mintech/utils/fmi/JNIException.h"
#include "com/mintech/utils/fmi/JNIError.h"
#include "com/mintech/utils/fmi/FMIException.h"
#include "java/lang/Object_interface.h"
#include "java/security/Key_interface.h"

#include "com/mintech/utils/fmi/builtin/arrays/FByteArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FByteArray;
}}}}}} //Close namespace

namespace java{
	namespace security{
class Key_interface;
}} //Close namespace


using namespace com::mintech::utils::fmi;
using namespace com::mintech::utils::fmi::builtin::arrays;
using namespace java::security;

namespace java{
	namespace security{
class PublicKey_interface;

class DLL_EXPORT PublicKey_interface :  public java::security::Key_interface
{
public:
//Public Methods
	//Destructor
	virtual ~PublicKey_interface() { }

	virtual string getAlgorithm() = 0;

	virtual FByteArray getEncoded() = 0;

	virtual string getFormat() = 0;

	//get method for the object name
	virtual const char* getFullName() = 0;

	//get / set methods for the Java object reference
	virtual jobject getReference() const		{ return m_ref;	}

	virtual void setReference(jobject ref)		{ m_ref = ref;	}

};

}} //Close namespace



#endif
