///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'ClassLoader'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_LANGCLASSLOADER_STUB_H
	#define JAVA_LANGCLASSLOADER_STUB_H




namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace java{
	namespace lang{
class Class;
}} // close namespace

namespace java{
	namespace lang{
class ClassLoader;
}} // close namespace

namespace java{
	namespace net{
class URL;
}} // close namespace

namespace java{
	namespace io{
class InputStream;
}} // close namespace

namespace java{
	namespace util{
class Enumeration;
}} // close namespace

namespace java{
	namespace lang{
class Object;
}} // close namespace


using com::mintech::utils::fmi::JNIException;
using java::lang::Class;
using java::lang::ClassLoader;
using java::net::URL;
using java::io::InputStream;
using java::util::Enumeration;
using java::lang::Object;

namespace java{
	namespace lang{
class ClassLoader_stub;


class DLL_EXPORT ClassLoader_stub : public Object_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	ClassLoader_stub();

	// constructor with jobject parameter for methods that return this object
	ClassLoader_stub(jobject obj);

	// destructor
	~ClassLoader_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//ClassLoader Public methods
	/* throws java.lang.ClassNotFoundException */
	java::lang::Class loadClass(const string& p1);

	static 	java::lang::ClassLoader getSystemClassLoader();

	java::net::URL getResource(const string& p1);

	java::io::InputStream getResourceAsStream(const string& p1);

	static 	java::net::URL getSystemResource(const string& p1);

	static 	java::io::InputStream getSystemResourceAsStream(const string& p1);

	void clearAssertionStatus();

	java::lang::ClassLoader getParent();

	/* throws java.io.IOException */
	java::util::Enumeration getResources(const string& p1);

	/* throws java.io.IOException */
	static 	java::util::Enumeration getSystemResources(const string& p1);

	void setClassAssertionStatus(const string& p1, const jboolean p2);

	void setDefaultAssertionStatus(const jboolean p1);

	void setPackageAssertionStatus(const string& p1, const jboolean p2);

//////////////////////////////////
// end of ClassLoader Public methods

//////////////////////////////
// public data members methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;
	static jmethodID method_5_ID;
	static jmethodID method_6_ID;
	static jmethodID method_7_ID;
	static jmethodID method_8_ID;
	static jmethodID method_9_ID;
	static jmethodID method_10_ID;
	static jmethodID method_11_ID;
	static jmethodID method_12_ID;
	static jmethodID method_13_ID;
	static jmethodID method_14_ID;

};


}} // close namespace

#endif
