///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.lang.Iterable



#if !defined JAVA_LANG_ITERABLE_H
	#define JAVA_LANG_ITERABLE_H


#include "java/lang/Iterable_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/lang/Iterable_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace lang{

class Iterable;


class DLL_EXPORT Iterable : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//Iterable Public methods
	java::util::Iterator iterator();

//End of Iterable Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	Iterable();

	//Copy constructor
	Iterable(const Iterable& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	Iterable(Iterable_stub* stub);

	//Constructor with jobject for returned objects
	Iterable(jobject obj);

	//Constructor with const int for handling NULL
	Iterable(const int null);

	//Set the stub
	void setStub(Iterable_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	Iterable& operator=(const Iterable& copy);

	//operator= for NULL
	Iterable& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(Iterable& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(Iterable& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static Iterable castFrom_Object(const Object& base);
};


}} //Close namespace



#endif
