///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//It represents the Java object 'Object_interface'.
//This file includs the necessary wrappings for the JNI calls to the Java object.

#if !defined JAVA_LANG_OBJECT_INTERFACE_H
#define JAVA_LANG_OBJECT_INTERFACE_H

#ifdef WIN32
	#define FMI_INT64 __int64
#else
	#define FMI_INT64 long long
#endif

#include "com/mintech/utils/fmi/JNIException.h"
#include "com/mintech/utils/fmi/JNIError.h"
#include "com/mintech/utils/fmi/FMIException.h"

#include <string>
using namespace std;

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace java{
	namespace lang{
class Class;
}} //Close namespace

namespace java{
	namespace lang{
class Object;
}} //Close namespace

using namespace com::mintech::utils::fmi;
using namespace java::lang;

namespace java{
	namespace lang{
class Object_interface;

class DLL_EXPORT Object_interface
{
public:
//Public Methods
	//Destructor
	virtual ~Object_interface() { }

	//get method for the object name
	virtual const char* getFullName() = 0;

	//get / set methods for the Java object reference
	virtual jobject getReference() const	{ return m_ref;	}

	virtual void setReference(jobject ref)	{ m_ref = ref;	}

	//A global reference to this object
	//This reference is for the JVM use
	jobject m_ref;
};

}} //Close namespace

#endif