///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.io.Serializable



#if !defined JAVA_IO_SERIALIZABLE_H
	#define JAVA_IO_SERIALIZABLE_H


#include "java/io/Serializable_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/io/Serializable_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace io{

class Serializable;


class DLL_EXPORT Serializable : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	Serializable();

	//Copy constructor
	Serializable(const Serializable& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	Serializable(Serializable_stub* stub);

	//Constructor with jobject for returned objects
	Serializable(jobject obj);

	//Constructor with const int for handling NULL
	Serializable(const int null);

	//Set the stub
	void setStub(Serializable_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	Serializable& operator=(const Serializable& copy);

	//operator= for NULL
	Serializable& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(Serializable& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(Serializable& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static Serializable castFrom_Object(const Object& base);
};


}} //Close namespace



#endif
