///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.util.Collection



#if !defined JAVA_UTIL_COLLECTION_H
	#define JAVA_UTIL_COLLECTION_H


#include "java/util/Collection_stub.h"
#include "java/lang/Iterable.h"



//These incudes are needed for the methods of the Stub
#include "java/util/Collection_interface.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace java{
	namespace lang{
class Iterable;
}} //Close namespace


using namespace com::mintech::utils::fmi;
using namespace java::lang;

namespace java{
	namespace util{

class Collection;


class DLL_EXPORT Collection :  public virtual java::lang::Iterable{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//Collection Public methods
	bool add(const Object& p1);

	void clear();

	bool contains(const Object& p1);

	bool isEmpty();

	bool addAll(const Collection& p1);

	java::util::Iterator iterator();

	jint size();

	FObjectArray toArray();

	bool remove(const Object& p1);

	bool containsAll(const Collection& p1);

	bool removeAll(const Collection& p1);

	bool retainAll(const Collection& p1);

//End of Collection Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	Collection();

	//Copy constructor
	Collection(const Collection& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	Collection(Collection_stub* stub);

	//Constructor with jobject for returned objects
	Collection(jobject obj);

	//Constructor with const int for handling NULL
	Collection(const int null);

	//Set the stub
	void setStub(Collection_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	Collection& operator=(const Collection& copy);

	//operator= for NULL
	Collection& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(Collection& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(Collection& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static Collection castFrom_Object(const Object& base);

	static Collection castFrom_Iterable(const Iterable& base);
};


}} //Close namespace



#endif
