///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//It represents the Java object 'Collection_interface'.
//This file includs the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_UTIL_COLLECTION_INTERFACE_H
	#define JAVA_UTIL_COLLECTION_INTERFACE_H



#include "com/mintech/utils/fmi/JNIException.h"
#include "com/mintech/utils/fmi/JNIError.h"
#include "com/mintech/utils/fmi/FMIException.h"
#include "java/lang/Object_interface.h"
#include "java/lang/Iterable_interface.h"

#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} //Close namespace

namespace java{
	namespace lang{
class Object;
}} //Close namespace

namespace java{
	namespace util{
class Collection;
}} //Close namespace

namespace java{
	namespace util{
class Iterator;
}} //Close namespace

namespace java{
	namespace lang{
class Iterable_interface;
}} //Close namespace


using namespace com::mintech::utils::fmi;
using namespace com::mintech::utils::fmi::builtin::arrays;
using namespace java::lang;
using namespace java::util;

namespace java{
	namespace util{
class Collection_interface;

class DLL_EXPORT Collection_interface :  public java::lang::Iterable_interface
{
public:
//Public Methods
	//Destructor
	virtual ~Collection_interface() { }

	virtual bool add(const Object& p1) = 0;

	virtual void clear() = 0;

	virtual bool contains(const Object& p1) = 0;

	virtual bool isEmpty() = 0;

	virtual bool addAll(const Collection& p1) = 0;

	virtual java::util::Iterator iterator() = 0;

	virtual jint size() = 0;

	virtual FObjectArray toArray() = 0;

	virtual bool remove(const Object& p1) = 0;

	virtual bool containsAll(const Collection& p1) = 0;

	virtual bool removeAll(const Collection& p1) = 0;

	virtual bool retainAll(const Collection& p1) = 0;

	//get method for the object name
	virtual const char* getFullName() = 0;

	//get / set methods for the Java object reference
	virtual jobject getReference() const		{ return m_ref;	}

	virtual void setReference(jobject ref)		{ m_ref = ref;	}

};

}} //Close namespace



#endif
