///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.util.Iterator



#if !defined JAVA_UTIL_ITERATOR_H
	#define JAVA_UTIL_ITERATOR_H


#include "java/util/Iterator_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/util/Iterator_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace util{

class Iterator;


class DLL_EXPORT Iterator : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//Iterator Public methods
	bool hasNext();

	java::lang::Object next();

	void remove();

//End of Iterator Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	Iterator();

	//Copy constructor
	Iterator(const Iterator& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	Iterator(Iterator_stub* stub);

	//Constructor with jobject for returned objects
	Iterator(jobject obj);

	//Constructor with const int for handling NULL
	Iterator(const int null);

	//Set the stub
	void setStub(Iterator_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	Iterator& operator=(const Iterator& copy);

	//operator= for NULL
	Iterator& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(Iterator& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(Iterator& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static Iterator castFrom_Object(const Object& base);
};


}} //Close namespace



#endif
