///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'List'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_UTILLIST_STUB_H
	#define JAVA_UTILLIST_STUB_H


#include "java/util/List_interface.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} // close namespace

namespace java{
	namespace lang{
class Object;
}} // close namespace

namespace java{
	namespace util{
class Collection;
}} // close namespace

namespace java{
	namespace util{
class Iterator;
}} // close namespace

namespace java{
	namespace util{
class List;
}} // close namespace

namespace java{
	namespace util{
class ListIterator;
}} // close namespace


using com::mintech::utils::fmi::JNIException;
using com::mintech::utils::fmi::builtin::arrays::FObjectArray;
using java::lang::Object;
using java::util::Collection;
using java::util::Iterator;
using java::util::List;
using java::util::ListIterator;

namespace java{
	namespace util{
class List_stub;


class DLL_EXPORT List_stub : public List_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	List_stub();

	// constructor with jobject parameter for methods that return this object
	List_stub(jobject obj);

	// destructor
	~List_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//List Public methods
	void add(const jint p1, const Object& p2);

	bool add(const Object& p1);

	jint indexOf(const Object& p1);

	void clear();

	bool contains(const Object& p1);

	bool isEmpty();

	jint lastIndexOf(const Object& p1);

	bool addAll(const jint p1, const Collection& p2);

	bool addAll(const Collection& p1);

	java::lang::Object get(const jint p1);

	java::util::Iterator iterator();

	jint size();

	FObjectArray toArray();

	bool remove(const Object& p1);

	java::lang::Object remove(const jint p1);

	java::lang::Object set(const jint p1, const Object& p2);

	bool containsAll(const Collection& p1);

	bool removeAll(const Collection& p1);

	bool retainAll(const Collection& p1);

	java::util::List subList(const jint p1, const jint p2);

	java::util::ListIterator listIterator(const jint p1);

	java::util::ListIterator listIterator();

//////////////////////////////////
// end of List Public methods

//////////////////////////////
// public data members methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;
	static jmethodID method_5_ID;
	static jmethodID method_6_ID;
	static jmethodID method_7_ID;
	static jmethodID method_8_ID;
	static jmethodID method_9_ID;
	static jmethodID method_10_ID;
	static jmethodID method_11_ID;
	static jmethodID method_12_ID;
	static jmethodID method_13_ID;
	static jmethodID method_14_ID;
	static jmethodID method_15_ID;
	static jmethodID method_16_ID;
	static jmethodID method_17_ID;
	static jmethodID method_18_ID;
	static jmethodID method_19_ID;
	static jmethodID method_20_ID;
	static jmethodID method_21_ID;
	static jmethodID method_22_ID;
	static jmethodID method_23_ID;

};


}} // close namespace

#endif
