///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.lang.reflect.GenericDeclaration



#if !defined JAVA_LANG_REFLECT_GENERICDECLARATION_H
	#define JAVA_LANG_REFLECT_GENERICDECLARATION_H


#include "java/lang/reflect/GenericDeclaration_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/lang/reflect/GenericDeclaration_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace lang{
		namespace reflect{

class GenericDeclaration;


class DLL_EXPORT GenericDeclaration : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//GenericDeclaration Public methods
	FObjectArray getTypeParameters();

//End of GenericDeclaration Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	GenericDeclaration();

	//Copy constructor
	GenericDeclaration(const GenericDeclaration& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	GenericDeclaration(GenericDeclaration_stub* stub);

	//Constructor with jobject for returned objects
	GenericDeclaration(jobject obj);

	//Constructor with const int for handling NULL
	GenericDeclaration(const int null);

	//Set the stub
	void setStub(GenericDeclaration_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	GenericDeclaration& operator=(const GenericDeclaration& copy);

	//operator= for NULL
	GenericDeclaration& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(GenericDeclaration& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(GenericDeclaration& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static GenericDeclaration castFrom_Object(const Object& base);
};


}}} //Close namespace



#endif
