///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//It represents the Java object 'GenericDeclaration_interface'.
//This file includs the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_LANG_REFLECT_GENERICDECLARATION_INTERFACE_H
	#define JAVA_LANG_REFLECT_GENERICDECLARATION_INTERFACE_H



#include "com/mintech/utils/fmi/JNIException.h"
#include "com/mintech/utils/fmi/JNIError.h"
#include "com/mintech/utils/fmi/FMIException.h"
#include "java/lang/Object_interface.h"

#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} //Close namespace

namespace java{
	namespace lang{
		namespace reflect{
class TypeVariable;
}}} //Close namespace


using namespace com::mintech::utils::fmi;
using namespace com::mintech::utils::fmi::builtin::arrays;
using namespace java::lang::reflect;

namespace java{
	namespace lang{
		namespace reflect{
class GenericDeclaration_interface;

class DLL_EXPORT GenericDeclaration_interface : public java::lang::Object_interface
{
public:
//Public Methods
	//Destructor
	virtual ~GenericDeclaration_interface() { }

	virtual FObjectArray getTypeParameters() = 0;

	//get method for the object name
	virtual const char* getFullName() = 0;

	//get / set methods for the Java object reference
	virtual jobject getReference() const		{ return m_ref;	}

	virtual void setReference(jobject ref)		{ m_ref = ref;	}

};

}}} //Close namespace



#endif
