///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'Method'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_LANG_REFLECTMETHOD_STUB_H
	#define JAVA_LANG_REFLECTMETHOD_STUB_H


#include "com/mintech/utils/fmi/builtin/arrays/FObjectArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FObjectArray;
}}}}}} // close namespace

namespace java{
	namespace lang{
		namespace reflect{
class Method;
}}} // close namespace

namespace java{
	namespace lang{
class Object;
}} // close namespace

namespace java{
	namespace lang{
		namespace annotation{
class Annotation;
}}} // close namespace

namespace java{
	namespace lang{
class Class;
}} // close namespace

namespace java{
	namespace lang{
		namespace reflect{
class TypeVariable;
}}} // close namespace

namespace java{
	namespace lang{
		namespace reflect{
class Type;
}}} // close namespace

namespace java{
	namespace lang{
		namespace reflect{
class AccessibleObject;
}}} // close namespace


using com::mintech::utils::fmi::JNIException;
using com::mintech::utils::fmi::builtin::arrays::FObjectArray;
using java::lang::reflect::Method;
using java::lang::Object;
using java::lang::annotation::Annotation;
using java::lang::Class;
using java::lang::reflect::TypeVariable;
using java::lang::reflect::Type;
using java::lang::reflect::AccessibleObject;

namespace java{
	namespace lang{
		namespace reflect{
class Method_stub;


class DLL_EXPORT Method_stub : public Object_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	Method_stub();

	// constructor with jobject parameter for methods that return this object
	Method_stub(jobject obj);

	// destructor
	~Method_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//Method Public methods
	jint getModifiers();

	string getName();

	java::lang::annotation::Annotation getAnnotation(const Class& p1);

	FObjectArray getDeclaredAnnotations();

	java::lang::Class getDeclaringClass();

	FObjectArray getParameterTypes();

	java::lang::Class getReturnType();

	FObjectArray getTypeParameters();

	bool isSynthetic();

	string toGenericString();

	java::lang::Object getDefaultValue();

	FObjectArray getExceptionTypes();

	FObjectArray getGenericExceptionTypes();

	FObjectArray getGenericParameterTypes();

	java::lang::reflect::Type getGenericReturnType();

	FObjectArray getParameterAnnotations();

	bool isBridge();

	bool isVarArgs();

	FObjectArray getAnnotations();

	bool isAnnotationPresent(const Class& p1);

	bool isAccessible();

	/* throws java.lang.SecurityException */
	void setAccessible(const jboolean p1);

//////////////////////////////////
// end of Method Public methods

//////////////////////////////
// public data members methods
	////////////////////////////////////////
	// public data members retrieval methods
	//'final' fields
	static jint get_PUBLIC();

	static jint get_DECLARED();

	//////////////////////////////////
	// public data members set methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;
	static jmethodID method_5_ID;
	static jmethodID method_6_ID;
	static jmethodID method_7_ID;
	static jmethodID method_8_ID;
	static jmethodID method_9_ID;
	static jmethodID method_10_ID;
	static jmethodID method_11_ID;
	static jmethodID method_12_ID;
	static jmethodID method_13_ID;
	static jmethodID method_14_ID;
	static jmethodID method_15_ID;
	static jmethodID method_16_ID;
	static jmethodID method_17_ID;
	static jmethodID method_18_ID;
	static jmethodID method_19_ID;
	static jmethodID method_20_ID;
	static jmethodID method_21_ID;
	static jmethodID method_22_ID;
	static jmethodID method_23_ID;

	// IDs for static data members
	static jfieldID staticField_1_ID;
	static jfieldID staticField_2_ID;

};


}}} // close namespace

#endif
