///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.lang.reflect.Type



#if !defined JAVA_LANG_REFLECT_TYPE_H
	#define JAVA_LANG_REFLECT_TYPE_H


#include "java/lang/reflect/Type_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/lang/reflect/Type_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace lang{
		namespace reflect{

class Type;


class DLL_EXPORT Type : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	Type();

	//Copy constructor
	Type(const Type& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	Type(Type_stub* stub);

	//Constructor with jobject for returned objects
	Type(jobject obj);

	//Constructor with const int for handling NULL
	Type(const int null);

	//Set the stub
	void setStub(Type_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	Type& operator=(const Type& copy);

	//operator= for NULL
	Type& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(Type& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(Type& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static Type castFrom_Object(const Object& base);
};


}}} //Close namespace



#endif
