///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.lang.reflect.TypeVariable



#if !defined JAVA_LANG_REFLECT_TYPEVARIABLE_H
	#define JAVA_LANG_REFLECT_TYPEVARIABLE_H


#include "java/lang/reflect/TypeVariable_stub.h"
#include "java/lang/reflect/Type.h"



//These incudes are needed for the methods of the Stub
#include "java/lang/reflect/TypeVariable_interface.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace java{
	namespace lang{
		namespace reflect{
class Type;
}}} //Close namespace


using namespace com::mintech::utils::fmi;
using namespace java::lang::reflect;

namespace java{
	namespace lang{
		namespace reflect{

class TypeVariable;


class DLL_EXPORT TypeVariable :  public virtual java::lang::reflect::Type{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//TypeVariable Public methods
	string getName();

	FObjectArray getBounds();

	java::lang::reflect::GenericDeclaration getGenericDeclaration();

//End of TypeVariable Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	TypeVariable();

	//Copy constructor
	TypeVariable(const TypeVariable& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	TypeVariable(TypeVariable_stub* stub);

	//Constructor with jobject for returned objects
	TypeVariable(jobject obj);

	//Constructor with const int for handling NULL
	TypeVariable(const int null);

	//Set the stub
	void setStub(TypeVariable_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	TypeVariable& operator=(const TypeVariable& copy);

	//operator= for NULL
	TypeVariable& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(TypeVariable& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(TypeVariable& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static TypeVariable castFrom_Object(const Object& base);

	static TypeVariable castFrom_Type(const Type& base);
};


}}} //Close namespace



#endif
