///////////////////////////////////////////////////////////////////////
// this header file was generated by FMI code generator.
// FMI Version: 7.6; Build: 2
// it represents the Java object 'Certificate'.
// this file includes the necessary wrappings for the JNI calls to the Java object.


#if !defined JAVA_SECURITY_CERTCERTIFICATE_STUB_H
	#define JAVA_SECURITY_CERTCERTIFICATE_STUB_H


#include "com/mintech/utils/fmi/builtin/arrays/FByteArray.h"


namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class JNIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
class FMIException;
}}}}

namespace com{
	namespace mintech{
		namespace utils{
			namespace fmi{
				namespace builtin{
					namespace arrays{
class FByteArray;
}}}}}} // close namespace

namespace java{
	namespace lang{
class Object;
}} // close namespace

namespace java{
	namespace security{
class PublicKey;
}} // close namespace

namespace java{
	namespace lang{
class Class;
}} // close namespace


using com::mintech::utils::fmi::JNIException;
using com::mintech::utils::fmi::builtin::arrays::FByteArray;
using java::lang::Object;
using java::security::PublicKey;
using java::lang::Class;

namespace java{
	namespace security{
		namespace cert{
class Certificate_stub;


class DLL_EXPORT Certificate_stub : public Object_interface
{
public:
//////////////////////
// public Constructors
// these constructors are for the C++ stubs. They do not create Java objects!

	// default constructor
	Certificate_stub();

	// constructor with jobject parameter for methods that return this object
	Certificate_stub(jobject obj);

	// destructor
	~Certificate_stub();

//////////////////
// utility methods
	// initialize all the IDs
	static void initialize();

	// get the object's full name
	virtual const char* getFullName();

	// get the class holder
	jclass getCls();

// end utility methods
//////////////////////

///////////////////////////////////////
// public methods from java.lang.object
	string toString();


// end of methods from java.lang.Object
///////////////////////////////////////


//////////////////////////////////
//Certificate Public methods
	string getType();

	/* throws java.security.cert.CertificateException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException, java.security.NoSuchProviderException, java.security.SignatureException */
	void verify(const PublicKey& p1);

	/* throws java.security.cert.CertificateException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException, java.security.NoSuchProviderException, java.security.SignatureException */
	void verify(const PublicKey& p1, const string& p2);

	/* throws java.security.cert.CertificateEncodingException */
	FByteArray getEncoded();

	java::security::PublicKey getPublicKey();

//////////////////////////////////
// end of Certificate Public methods

//////////////////////////////
// public data members methods
//end public data members methods
/////////////////////////////////

private:
	// indicates if an instance of this stub has already been created
	static bool m_firstTime;

	// class holder (defined static to allow accessibility to static methods)
	static jclass m_cls;

	// the object's full name
	static char* m_objectName;

private:
	// java.lang.Class getName() method's ID
	static jmethodID m_getName_method_ID;

	// java.lang.Object Methods' IDs
	static jmethodID method_1_ID;

	// methods' IDs
	static jmethodID method_2_ID;
	static jmethodID method_3_ID;
	static jmethodID method_4_ID;
	static jmethodID method_5_ID;
	static jmethodID method_6_ID;

};


}}} // close namespace

#endif
