///////////////////////////////////////////////////////////////////////
//This header file was generated by FMI code generator.
//FMI Version: 7.6; Build: 2
//This is the declaration of the smart pointer for class 'java.net.FileNameMap



#if !defined JAVA_NET_FILENAMEMAP_H
	#define JAVA_NET_FILENAMEMAP_H


#include "java/net/FileNameMap_stub.h"



//These incudes are needed for the methods of the Stub
#include "java/net/FileNameMap_interface.h"


using namespace com::mintech::utils::fmi;

namespace java{
	namespace net{

class FileNameMap;


class DLL_EXPORT FileNameMap : public virtual java::lang::Object
{
public:
/////////////////////
//Public Stub methods

//Public methods from java.lang.object
	string toString();

//End of methods from java.lang.Object


//FileNameMap Public methods
	string getContentTypeFor(const string& p1);

//End of FileNameMap Public methods

//End public Stub methods

public:
////////////////////////////////
//Internal Smart Pointer methods

	//Constructor / Destructor
	FileNameMap();

	//Copy constructor
	FileNameMap(const FileNameMap& copy);

	//Constructor with stub for returned objects (a new stub should return as a smart pointer)
	FileNameMap(FileNameMap_stub* stub);

	//Constructor with jobject for returned objects
	FileNameMap(jobject obj);

	//Constructor with const int for handling NULL
	FileNameMap(const int null);

	//Set the stub
	void setStub(FileNameMap_interface* stub);

	//Get the stub
	Object_interface* getStub() const;

	//operator= for two smart pointers
	FileNameMap& operator=(const FileNameMap& copy);

	//operator= for NULL
	FileNameMap& operator=(const int null);

	//operator== for two smart pointers
	bool operator==(FileNameMap& obj);

	//operator== for NULL
	bool operator==(const int null);

	//operator!= for two smart pointers
	bool operator!=(FileNameMap& obj);

	//operator!= for NULL
	bool operator!=(const int null);

	//isInstanceOf: checks if this object is an instance of the class represented by the
	//smart pointer parameter
	bool isInstanceOf(Object& checkObj);

	//isAssignableFrom: checks if this object can be safely cast from checkObj
	static bool isAssignableFrom(const Object& checkObj);

	//Casting methods
	static FileNameMap castFrom_Object(const Object& base);
};


}} //Close namespace



#endif
